# Problem 1

In [7]:
# 1 - numpy kütüphanesini import edin  
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matrix = np.random.randint(0, 11, size=(5,))
print(matrix)

# 3 - matris'in boyutunu öğrenin
print(matrix.shape)

# 4 - matris'i yeniden boyutlandırın
reshaped_matrix = matrix.reshape(1, 5)
print(reshaped_matrix)
# 5 - matris'in boyut sayısını öğrenin
print(reshaped_matrix.ndim)


[7 6 6 8 9]
(5,)
[[7 6 6 8 9]]
2


# Problem 2

In [15]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
x=np.arange(1,10,2)
print(x)

# 2 - Oluşturduğunuz matrisi parçalayın
split_x= np.split(x,[3])
print(split_x)

# 3 - Parçalanmış matrisleri birleştirin
merge_x=np.concatenate(split_x)
print(merge_x)


[1 3 5 7 9]
[array([1, 3, 5]), array([7, 9])]
[1 3 5 7 9]


# Problem 3

In [17]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
y=np.arange(5,100,2)
print(y)

# 2 - matris'in özelliklerini inceleyin
print(y.ndim)
print(y.shape)
print(y.size)
print(y.dtype)


[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51
 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99]
1
(48,)
48
int64
