# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
x = np.array([9, 2, 3, 8, 4])
print(x)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
x.sort()
print(x)


[9 2 3 8 4]
[2 3 4 8 9]


# Problem 2

In [27]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
y = np.array([10,15,30,45,60])
print(y)



# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
a=np.arange(5,15)
print(a)
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
b=np.arange(50,100,5)
print(b)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
c=np.zeros(10)
print(c)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
d=np.ones(10)
print(d)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
e=np.linspace(0,100,5)
print(e)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
f=np.random.randint(10,30,5)
print(f)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
g=np.random.uniform(-1,1,10)
print(g)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
h=np.random.randint(10,50,size=(3,5))
print(h)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
row_sums = h.sum(axis=1)
col_sums = h.sum(axis=0)
print(row_sums)
print(col_sums)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
max_value = h.max()
min_value = h.min()
mean = h.mean()
print(max_value)
print(min_value)
print(mean)


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
max_index = np.unravel_index(np.argmax(h), h.shape)
print(max_index)


# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
i=np.arange(10,20)
print(i[0:3])


# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(i[::-1])


# 15- Üretilen matrisin ilk satırını seçiniz.
print(h[0, :])



# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(h[1,2])


# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(h[:, 0])


# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(np.square(h))


# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
new_h=np.random.randint(-50,50,size=(3,5))
print(new_h)
even_new_h=new_h[(new_h%2==0)]
print(even_new_h[even_new_h>0])




[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[20 23 20 26 12]
[ 0.05632026 -0.65670338 -0.73121046 -0.43492877 -0.2071853   0.33560536
 -0.5506072  -0.26538146 -0.75968943  0.33406454]
[[13 34 39 15 27]
 [29 37 42 30 37]
 [43 25 42 23 43]]
[128 175 176]
[ 85  96 123  68 107]
43
13
31.933333333333334
(np.int64(2), np.int64(0))
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]
[13 34 39 15 27]
42
[13 29 43]
[[ 169 1156 1521  225  729]
 [ 841 1369 1764  900 1369]
 [1849  625 1764  529 1849]]
[[ 40 -29  -3 -35 -42]
 [ 44 -30 -43 -32  46]
 [ 11   8  41 -34   3]]
[40 44 46  8]
